"""fix hashed_password column length

Revision ID: c4175b34d60b
Revises: d3a5a3d36582
Create Date: 2026-03-25 13:06:48.558899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4175b34d60b'
down_revision: Union[str, Sequence[str], None] = 'd3a5a3d36582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=72),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=72),
               existing_nullable=False)
    # ### end Alembic commands ###
